server:
  port: 8080

app:
  cors:
    allowed-origins: "http://localhost:3000"

spring:
  application:
    name: portfolio_be

  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_be
    username: postgres
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
